export { default as Dialog } from './Dialog.vue'
export { default as DialogTrigger } from './DialogTrigger.vue'
export { default as DialogContent } from './DialogContent.vue'
export { default as DialogHeader } from './DialogHeader.vue'
export { default as DialogTitle } from './DialogTitle.vue'
export { default as DialogDescription } from './DialogDescription.vue'
export { default as DialogClose } from './DialogClose.vue'
export type { DialogTriggerProps } from './DialogTrigger.vue'
export type { DialogContentProps } from './DialogContent.vue'
export type { DialogHeaderProps } from './DialogHeader.vue'
export type { DialogTitleProps } from './DialogTitle.vue'
export type { DialogDescriptionProps } from './DialogDescription.vue'
export type { DialogCloseProps } from './DialogClose.vue'

